source=wlan0:name=omni,info_antenna_type=omni,info_antenna_gain=5

source=wlan1:name=cone,info_antenna_type=directional,\
    info_antenna_gain=7,info_antenna_beamwidth=60,/
    info_antenna_orientation=0

source=hci0:name=ble

channel_hop=true
channel_hop_speed=5/sec

#REST API - set credentials here
httpd_username=kismet
httpd_password=your_password_here
httpd_bind_address=127.0.0.1 # local only
httpd_port=2501

log_prefix=/home/pi/kismet_logs
log_types=kismetdb
